name: AP2 Repository Monitor

on:
  schedule:
    # Run every 5 days at 8:00 AM UTC
    - cron: '0 8 */5 * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  monitor-ap2-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ap2-monitor/requirements.txt
    
    - name: Run AP2 monitoring
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ap2-monitor
        python monitor.py
    
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ap2-monitor/data/
        git diff --staged --quiet || git commit -m "Update AP2 monitoring results - $(date '+%Y-%m-%d')"
        git push